### ISSUE TITLE
Will nested Populate work?

### ISSUE THREAD

**Issue by kethan** [MichaelErmer/feathers-populate-hook#3]
Hi, 

Will deep population work ? like nested Users->Posts->Comments??

**Comment by MichaelErmer** [comment]
yes, unless you add $populate: false to the query in the populate definition.

https://github.com/MichaelErmer/feathers-populate-hook#query-options

**Comment by brianjohnhanna** [comment]
Is there an example of how you might use deep population? Nested dot notation doesn't seem to work for me.

    populate({
      createdBy: {
        service: 'users',
         f_key: '_id',
         one: true,
      },
      likes: {
        service: 'users',
        f_key: '_id'
      },
      comments: {
         service: 'comments',
         f_key: '_id',
      },
      'comments.createdBy': { // this doesn't work :(
        service: 'users',
        f_key: '_id',
        one: true
      }
    })

I haven't set `$populate` anywhere. Also tried adding the following to the `comments` object with no luck.

    query: {
        $populate: 'createdby'
    }

**Comment by MichaelErmer** [comment]
Add it to the nested service ;)
