### ISSUE TITLE
Error 500 - Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by jonathanroze** [MichaelErmer/feathers-populate-hook#4]
Hey ! I've this error when i want to populate my object ! 

I've set this hook on my owners service (ownerId, userId, eventId) and i need to link an event by eventId so i use your hook like that : 

```
const { authenticate } = require('feathers-authentication').hooks;
const populate = require('feathers-populate-hook');

const bindData = require('../../hooks/bind-data');

const EventSchema = {
   event: { // Destination key
   service: 'events', // Foreign service
   f_key: 'eventId',  // Foreign key
   l_key: 'eventId',  // Local key
  },
};

module.exports = {
  before: {
    all: [authenticate('jwt'), populate.compatibility()],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  after: {
    all: [],
    find: [populate({EventSchema})],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};

```

And i've this error : 

```
info: error: owners - Method: find: Cannot read property 'replace' of undefined
error:  TypeError: Cannot read property 'replace' of undefined
    at stripSlashes (/Users/jr/Documents/Projets/ZProjects/proj/server/node_modules/feathers-commons/lib/utils.js:33:14)
    at EventEmitter.service (/Users/jr/Documents/Projets/ZProjects/proj/server/node_modules/feathers/lib/application.js:44:50)
    at populateField (/Users/jr/Documents/Projets/ZProjects/proj/server/node_modules/feathers-populate-hook/lib/populate/index.js:72:25)
    at Array.map (native)
    at populate (/Users/jr/Documents/Projets/ZProjects/proj/server/node_modules/feathers-populate-hook/lib/populate/index.js:79:47)
    at Array.map (native)
    at Object.<anonymous> (/Users/jr/Documents/Projets/ZProjects/proj/server/node_modules/feathers-populate-hook/lib/populate/index.js:84:62)
```
Feathers version : 2.1.7
Database Connector : KnexJS - Mysql

And it's possible to put this hook on before ? To filter on data which are added?
I need to get my own events with a date superior or equal to current date ! Do you have an idea to do that?

thx

**Comment by Ernoff** [comment]
@Clowning It is a tad difficult to fully comprehend what you are trying to accomplish here. Aside from populating, you mentioned linking an event by eventId.

The linking must have already been done when saving to Owners model.
The library helps to populate the fields that are referenced by Schema.Types.ObjectId. 

That being said, I can point some things out to you from the above code. 
The eventId repetition shouldn't be there. A sample event schema should look like this:

```
const EventSchema = { 
   event: { // name of the field that has Schema.Types.ObjectId linked to it ie the associated key 
   service: 'events', // name of the service that references the eventid
   f_key: 'id',  // the key used for association 
  }
};

```

and your after hook should look like this. Notice i removed the curly braces cos EventSchema is already defined as an object

```
after: {
    all: [],
    find: [populate(EventSchema)],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },
```
To get the dates greater than or equal to today, you will need to define a query after the populate and use hooks.params.knex to customize the find result.

You can reach out to me if you have further concerns

**Comment by MichaelErmer** [comment]
@Ernoff Thanks for helping out, I also added a new option to overwrite the params with `0.4`, see https://github.com/MichaelErmer/feathers-populate-hook
